# Generated by Django 5.0.7 on 2024-08-10 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_post_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='category',
            new_name='Type',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='blog_category',
        ),
    ]
