# Generated by Django 5.0.7 on 2024-08-10 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_rename_category_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='blog_category',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
