# Generated by Django 5.0.7 on 2024-08-07 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_customuser_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='updated_at',
        ),
    ]
