# Generated by Django 5.0.7 on 2024-08-08 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
