# Generated by Django 5.0.7 on 2024-08-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_remove_customuser_user_name_alter_customuser_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/files/profile_images'),
        ),
    ]
